import HomePage from "@/container/HomePage";
import getAllPosts from "@/data/posts/get-all-posts";
import { AllPosts } from "@/domain/posts/posts";
import { GetStaticProps } from "next";
import Head from "next/head";

export type HomeProps = {
    posts: AllPosts;
};

export default function Home({ posts }: HomeProps) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomePage posts={posts} />
        </>
    );
}

export const getStaticProps: GetStaticProps = async () => {
    const posts = await getAllPosts();

    return {
        props: { posts },
    };
};
